---
title: "Modeling Manhattan Precincts"
output: html_notebook
---

## Setup

```{r message=TRUE}
library(raster) # load before dplyr to avoid select bs

library(dplyr)
library(ggplot2)
library(sf)

# New packages
library(nnet)
library(xgboost)

# Load data
load(file="precinct.Rdata")
ggplot(combined, aes(x=x,y=y,color=factor(precinct))) + geom_point()
```


## Get Manhattan Info

```{r}
nybb = st_read("/data/nyc_parking/nybb/", quiet=TRUE)
manh = nybb %>% filter(BoroName == "Manhattan")
#plot(manh,axes=TRUE)

library(raster)
ext = st_bbox(manh) %>% .[c("xmin","xmax","ymin","ymax")] %>% extent()
r = raster(ext, ncol=400, nrow=556)
r = rasterize(as(manh,"Spatial"),r)

load("/data/nyc_parking/manh_bound.Rdata")
extb = st_bbox(bound) %>% .[c("xmin","xmax","ymin","ymax")] %>% extent()
rb = raster(extb, ncol=100, nrow=300)
rb = rasterize(as(bound,"Spatial"),r)

par(mfrow=c(1,2))
plot(r,asp=0)
plot(rb,asp=0)
```

### Get prediction locations

```{r}
pred_cells = which(!is.na(rb[]))
pred_locs = xyFromCell(rb, pred_cells) %>% as.data.frame() %>% tbl_df()
#look = pred_locs%>%filter(x>=-73.981900 & x<=-73.949300)%>%arrange(desc(x))
plot(pred_locs, pch=16, cex=0.1)
```

## Model 4 - xgboost

```{r}
library(xgboost)
# generate fake data for central park
combined %<>% filter(precinct!=22)
x_span = seq(-73.981600, -73.94950, 0.0003526966)
y_span = seq(40.76458,40.80055,0.0003527358)
x = sample(x_span, 20000,replace = TRUE)
y = sample(y_span, 20000,replace = TRUE)
is22 = function(x){
 if ((x[2]<=1.36555*x[1]+141.794) &&
     (x[2]<=8.86415-0.431818*x[1]) &&
     (x[2]>=1.36134*x[1]+141.467) &&
     (x[2]>=9.66207-0.420455*x[1]))
   return(TRUE)
 else
   return(FALSE)
}
in22 = cbind(x,y) %>% apply(1,is22)
central = cbind(precinct = rep(22,length(x)),x,y) %>% .[in22,] %>% as_data_frame
combined %<>% filter(!combined[,c("x","y")] %>% apply(1,is22))
combined = bind_rows(combined, central)
combined = combined[sample(1:nrow(combined),nrow(combined),replace = FALSE),]

precincts = factor(combined$precinct) %>% levels()
y = (factor(combined$precinct) %>% as.integer()) - 1L
x = combined %>% select(x,y) %>% as.matrix()

x1 = sample(x_span, 60000, replace = TRUE)
y1 = sample(y_span, 60000, replace = TRUE)
in221 = cbind(x1,y1) %>% apply(1,is22)
central1 = cbind(precinct = rep(22,length(x1)),x1,y1) %>% .[in221,] %>% as_data_frame
combined1 = combined %>% filter(!combined[,c("x","y")]%>%apply(1,is22))
combined1 = bind_rows(combined1, central1%>%setNames(c("precinct","x","y")))
combined1 = combined1[sample(1:nrow(combined1),nrow(combined1),replace = FALSE),]

precincts1 = factor(combined1$precinct) %>% levels()
ynew = (factor(combined1$precinct) %>% as.integer()) - 1L
xnew = combined1 %>% select(x,y) %>% as.matrix()


m = xgboost(data=x, label=y, nthead=4, nround=25, max_depth = 15,objective="multi:softmax", num_class=length(precincts))
table(combined$precinct)

m = xgboost(data=xnew, label=ynew, nthead=4, nround=25, max_depth = 15,objective="multi:softmax", num_class=length(precincts))


library(class)
train = combined[1:10000,]
test = combined[11000:12000,]
knn.fit = knn(train[,c("x","y")],test[,c("x","y")], factor(train$precinct), k = 22)
mean(test$precinct!=knn.fit)
ggplot(cbind(test[,c("x","y")], pred=knn.fit), aes(x=x,y=y,color=factor(pred))) + geom_point()

kn = c(21,22,23)
yn = factor(combined$precinct)
error = matrix(0,10,3)
library(caret)
folds = createFolds(1:1574104)%>%setNames(NULL)
for(i in 1:3){
  for(j in 1:10){
    knn.fit = knn(x[-folds[[j]],], x[folds[[j]],], yn[-folds[[j]]], k = kn[i],use.all=FALSE)
    error[j,i]=mean(yn[folds[[j]]] != knn.fit)
  }
}


pred_xg = predict(m, newdata=as.matrix(pred_locs))
pred_xg = precincts[pred_xg+1]
ggplot(cbind(pred_locs, pred=pred_xg), aes(x=x,y=y,color=factor(pred))) + geom_point()
```


## Rasters -> Polygons

```{r}
r_xg = rb
r_xg[pred_cells] = as.numeric(pred_xg)
plot(r_xg)
```


## Polygonize

```{r}
source("polygonizer.R")
p = polygonizer(r_xg)
p = st_transform(p, 4326)
plot(p)

st_write(p,"precincts.json", "data", driver="GeoJSON", quiet=TRUE)
```